include:
  - board: nice_nano_v2
    shield: corneish_zen_v2_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: corneish_zen_v2_right
  - board: nice_nano_v2
    shield: settings_reset
